export enum ErrorTypeEnum {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH',
  DEFAULT = 'DEFAULT',
  SERVER_ERROR = 'SERVER_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  AUTHENTICATED = 'AUTHENTICATED',
}
